name: Roljobs Technology Services Private Limited
favicon: null
layout_spectrum: 0.25196
typography_spectrum: 0.2509
title: Roljobs Technology Services Private Limited
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-0000-01
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#c7c7c7'
    - '#626262'
    - '#8c8c8c'
  brandStrength: 0.5
  lightness: 0.3125
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
