name: Roljobs Technology Services Private Limited
favicon: null
layout_spectrum: 0.19267
typography_spectrum: 0.98956
title: Roljobs Technology Services Private Limited
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-0000-01
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#069abe'
    - '#e77616'
    - '#322e2b'
    - '#7cc7d9'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.4375
  rhythmicContrast: 0.25
purpose: []
