name: Roljobs Technology Services Private Limited
favicon: null
layout_spectrum: 0.40153
typography_spectrum: 0.62307
title: Roljobs Technology Services Private Limited
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-0000-01
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cf3940'
    - '#000000'
    - '#f7a922'
    - '#584b06'
    - '#856d0b'
  brandStrength: 0.4375
  lightness: 1
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
