name: Roljobs Technology Services Private Limited
favicon: null
layout_spectrum: 0
typography_spectrum: 0.90368
title: Roljobs Technology Services Private Limited
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-0000-01
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#cccccc'
    - '#222222'
    - '#616161'
    - '#b01d27'
  brandStrength: 0
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
