name: Roljobs Technology Services Private Limited
favicon: null
layout_spectrum: 0.6401
typography_spectrum: 0.98956
title: Roljobs Technology Services Private Limited
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-0000-01
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4a2c13'
    - '#150d15'
    - '#003e60'
    - '#292636'
    - '#faf8fd'
  brandStrength: 0.625
  lightness: 0.625
  saturation: 0.4375
  rhythmicContrast: 0.25
purpose: []
