name: Roljobs Technology Services Private Limited
favicon: null
layout_spectrum: 0.40153
typography_spectrum: 0.62307
title: Roljobs Technology Services Private Limited
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-0000-01
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#14303f'
    - '#537a67'
    - '#948c79'
    - '#bdbbb1'
    - '#dde1e4'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
